yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@chakra-ui/provider@*":
    dependencies:
      "@chakra-ui/react-env": "*"
      "@chakra-ui/portal": "*"
  "@chakra-ui/icon@*":
    dependencies:
      "@chakra-ui/system": "*"